[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { version = "1.1.10", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
serde = { version = "1.0.219", features = ["derive"] }
