name: Build and Publish Docker Images

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Commit Hash
        id: get_commit_hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-ledger
          key: ${{ runner.os }}-ledger-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ledger-buildx-

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          build-args: |
            COMMIT_HASH=${{ env.hash }}
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache-ledger
          cache-to: type=local,dest=/tmp/.buildx-cache-ledger-new,mode=max
          tags: |
            ghcr.io/ldg-sh/ledger:${{ env.hash }}

      - name: Move updated Docker cache
        run: |
          rm -rf /tmp/.buildx-cache-ledger
          mv /tmp/.buildx-cache-ledger-new /tmp/.buildx-cache-ledger